server:
  port: 8080
  servlet:
    context-path: /nemo

spring:
  thymeleaf:
    cache: false
    mode: HTML
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/nemo?characterEncoding=utf-8
    username: root
    password:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8

mybatis:
  configuration:
    use-generated-keys: true
    use-column-label: true
    map-underscore-to-camel-case: true
  type-aliases-package: com.rumofuture.nemo.model.domain, com.rumofuture.nemo.model.entity
  mapper-locations: classpath:mappers/*.xml