server:
  port: 8090
  servlet:
    context-path: /nemo
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nemo
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: